### ISSUE TITLE
artifacts with jointbilateral

### ISSUE THREAD

**Issue by hooke007** [Artoriuz/glsl-joint-bilateral#1]
https://github.com/Artoriuz/glsl-joint-bilateral/commit/29c1932420542d25b712cb7f03fad68c3e783112
![Snipaste_2023-07-18_23-05-51](https://github.com/Artoriuz/glsl-joint-bilateral/assets/41094733/5568177f-adf3-41a4-94f5-848c76bac4d2)

**Comment by Artoriuz** [comment]
Can you provide me the original image so I can do some tests?

**Comment by hooke007** [comment]
https://github.com/hooke007/MPV_lazy/blob/obs/Temp/IMG/chroma-420.jpg

**Comment by Artoriuz** [comment]
Could you retest with https://github.com/Artoriuz/glsl-joint-bilateral/commit/a50418b0dc0e3aa3ece1d9d940dcbc2584a9753e?
