### ISSUE TITLE
Usage in iOS app for improving a depth map

### ISSUE THREAD

**Issue by alexfoxy** [Artoriuz/glsl-joint-bilateral#6]
Hey, this looks really interesting, how feasible do you think it would be to port it to a metal shader to use within an iOS app? I was hoping I could use a technique like this to improve the depth map captured by the camera for adding depth of field to photographs. I have been using an anti aliasing filter, which is quite good but bilateral filtering would be the next level.

Thanks!

**Comment by Artoriuz** [comment]
I have no idea, but the code itself is relatively simple so you shouldn't have any problems with it.
